service: cravingscompass-api
frameworkVersion: '4'

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_SERVICE_ROLE_KEY: ${env:SUPABASE_SERVICE_ROLE_KEY, ''}
    SUPABASE_SECRET_KEY: ${env:SUPABASE_SECRET_KEY, ''}
    SUPABASE_PUBLISHABLE_KEY: ${env:SUPABASE_PUBLISHABLE_KEY, ''}
    SUPABASE_ANON_KEY: ${env:SUPABASE_ANON_KEY, ''}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi:
          path: /
          method: '*'
      - httpApi:
          path: /{proxy+}
          method: '*'
